services:
  api:
    build:
      context: .
      target: dev
    container_name: golang_boilerplate
    volumes:
      - ./:/go/src/github.com/golang-boilerplate
    env_file:
      - configuration/env/dev.env
    ports:
      - 8181:8181

